# platform :ios, '8.0'
# use_frameworks!

target 'RAC-OC' do

pod 'Masonry', '~> 1.0.2'
pod 'ReactiveCocoa', '~> 4.0.2-alpha-1'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.12'

use_frameworks!

end
